// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-d5sNLnax_zTHXnHuyzGMYmVrfXWf1og',
    appId: '1:565885904617:android:9bc7b0f2a71157ecd1f278',
    messagingSenderId: '565885904617',
    projectId: 'bio-metric-c4d98',
    storageBucket: 'bio-metric-c4d98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB2AsogC0C0ub4Wouh6DmHwBgsNcSHQUA',
    appId: '1:565885904617:ios:5f3397248ac79430d1f278',
    messagingSenderId: '565885904617',
    projectId: 'bio-metric-c4d98',
    storageBucket: 'bio-metric-c4d98.firebasestorage.app',
    iosBundleId: 'com.example.virgilapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB2AsogC0C0ub4Wouh6DmHwBgsNcSHQUA',
    appId: '1:565885904617:ios:5f3397248ac79430d1f278',
    messagingSenderId: '565885904617',
    projectId: 'bio-metric-c4d98',
    storageBucket: 'bio-metric-c4d98.firebasestorage.app',
    iosBundleId: 'com.example.virgilapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCll-N8VV9QpcU1yJdqk5Jdd8c8FQsmiBI',
    appId: '1:565885904617:web:44e1da9df742bfeed1f278',
    messagingSenderId: '565885904617',
    projectId: 'bio-metric-c4d98',
    authDomain: 'bio-metric-c4d98.firebaseapp.com',
    storageBucket: 'bio-metric-c4d98.firebasestorage.app',
    measurementId: 'G-QYCNX289FL',
  );
}
